import type { ConfigSummary } from '../../data/types';
import { formatCount, formatDateTime, formatHour, formatPercent } from '../../lib/format';
import styles from './DashboardFooter.module.css';

interface DashboardFooterProps {
  config: ConfigSummary;
  generatedAt: string;
  /**
   * Whether a pipeline run produced this payload — see `App`'s
   * `analysisAvailable`. False on the file-import route, where `config` is
   * `buildFromCsv`'s placeholder rather than anybody's settings.
   */
  analysisAvailable: boolean;
}

/**
 * Methodology notes.
 *
 * Ported verbatim from the Python footer, including the "how to read this"
 * paragraph. That paragraph is the one place the report tells a reader that a
 * wide interval on short history is the honest answer rather than a defect,
 * so it is not decoration.
 *
 * **Every figure below describes a pipeline run, so none of it may be rendered
 * without one.** §12 flagged this footer's hazard when the CSV route was built
 * ("a future section that reads `config` unconditionally must check") and this
 * is that section. A raw export carries no configuration, so `buildFromCsv`
 * hands over `placeholderConfig()` — all zeros and empty strings — and reading
 * it unconditionally published "Interval level: 0%", "simulated from 0
 * bootstrap trajectories", "rolling origin, 0-day horizon, selection on" with
 * the metric name missing, and business hours of 00:00–00:00.
 *
 * Those are not empty states. They are false statements about settings, made in
 * the voice of the report's own methodology note — and a reader checking why an
 * import looked wrong found a footer telling them the interval level was zero.
 *
 * So the notes are gated on the same flag that gates the anomalies section, and
 * for the same reason: an absent methodology and a methodology of zeroes mean
 * different things, and the payload cannot tell them apart.
 */
export function DashboardFooter({ config, generatedAt, analysisAvailable }: DashboardFooterProps) {
  const { forecast, cv, data, business_hours: hours } = config;
  const holidays = [data.holiday_country, data.holiday_subdiv].filter(Boolean).join(' ');

  /*
   * The imported-file footer: provenance, and then it stops. No "how to read
   * this" paragraph about intervals that do not exist, and no "Generated by
   * call_forecast", because this view was not.
   */
  if (!analysisAvailable) {
    return (
      <footer className={styles.footer}>
        <p>
          <strong>How to read this.</strong> These figures describe the file that was
          imported — call volumes, durations, costs and arrival times exactly as exported.
          No forecast, model selection or anomaly rule ran, so there is no run
          configuration to report and no interval to interpret.
        </p>
        <p>Rendered from an imported file · {formatDateTime(generatedAt)}</p>
      </footer>
    );
  }

  return (
    <footer className={styles.footer}>
      <p>
        <strong>How to read this.</strong> Point forecasts are the model&rsquo;s best single
        guess; intervals show the range that backtest error suggests. Where history is short,
        the interval is the honest part of the answer.
      </p>
      <ul>
        <li>
          Interval level: {formatPercent(forecast.interval_level)} · simulated from{' '}
          {formatCount(forecast.n_simulations)} bootstrap trajectories
        </li>
        <li>
          Validation: rolling origin, {cv.horizon}-day horizon, selection on{' '}
          {cv.selection_metric.toUpperCase()}
        </li>
        <li>Holiday calendar: {holidays || '—'}</li>
        <li>
          Business hours: {formatHour(hours.start_hour)}–{formatHour(hours.end_hour)} · overnight
          window {formatHour(hours.overnight_start_hour)}–{formatHour(hours.overnight_end_hour)}
        </li>
      </ul>
      <p>Generated by call_forecast · {formatDateTime(generatedAt)}</p>
    </footer>
  );
}
