import type { ConfigSummary } from '../../data/types';
import { formatCount, formatDateTime, formatHour, formatPercent } from '../../lib/format';
import styles from './DashboardFooter.module.css';

interface DashboardFooterProps {
  config: ConfigSummary;
  generatedAt: string;
}

/**
 * Methodology notes.
 *
 * Ported verbatim from the Python footer, including the "how to read this"
 * paragraph. That paragraph is the one place the report tells a reader that a
 * wide interval on short history is the honest answer rather than a defect,
 * so it is not decoration.
 */
export function DashboardFooter({ config, generatedAt }: DashboardFooterProps) {
  const { forecast, cv, data, business_hours: hours } = config;
  const holidays = [data.holiday_country, data.holiday_subdiv].filter(Boolean).join(' ');

  return (
    <footer className={styles.footer}>
      <p>
        <strong>How to read this.</strong> Point forecasts are the model&rsquo;s best single
        guess; intervals show the range that backtest error suggests. Where history is short,
        the interval is the honest part of the answer.
      </p>
      <ul>
        <li>
          Interval level: {formatPercent(forecast.interval_level)} · simulated from{' '}
          {formatCount(forecast.n_simulations)} bootstrap trajectories
        </li>
        <li>
          Validation: rolling origin, {cv.horizon}-day horizon, selection on{' '}
          {cv.selection_metric.toUpperCase()}
        </li>
        <li>Holiday calendar: {holidays || '—'}</li>
        <li>
          Business hours: {formatHour(hours.start_hour)}–{formatHour(hours.end_hour)} · overnight
          window {formatHour(hours.overnight_start_hour)}–{formatHour(hours.overnight_end_hour)}
        </li>
      </ul>
      <p>Generated by call_forecast · {formatDateTime(generatedAt)}</p>
    </footer>
  );
}
