// @vitest-environment jsdom
import '@testing-library/jest-dom';
import { describe, expect, it } from 'vitest';
import { render, screen } from '@testing-library/react';
import { DashboardFooter } from './DashboardFooter';
import type { ConfigSummary } from '../../data/types';

/**
 * A real run's configuration, and the all-zero placeholder the import route
 * substitutes for it.
 *
 * The placeholder is copied from `buildFromCsv`'s `placeholderConfig()` rather
 * than imported, deliberately: this file's job is to pin what the footer does
 * when handed zeros, and it should keep doing that even if the parser's
 * placeholder changes shape.
 */
const REAL_CONFIG: ConfigSummary = {
  forecast: { horizons: [30, 60, 90], interval_level: 0.8, n_simulations: 500, targets: ['call_volume'] },
  cv: {
    horizon: 7,
    step: 7,
    initial_train_days: 42,
    min_folds: 3,
    selection_metric: 'mase',
    selection_tiebreaker: 'mae',
  },
  data: { holiday_country: 'US', holiday_subdiv: 'AZ' },
  business_hours: { start_hour: 8, end_hour: 17, overnight_start_hour: 22, overnight_end_hour: 6 },
  anomalies: {
    cost_overrun_pct: 25,
    duration_sigma: 3,
    missed_spike_sigma: 3,
    robust_z_threshold: 3.5,
    baseline_window_days: 28,
  },
  scenarios: {
    current_agents: 1,
    target_answer_seconds: 30,
    service_level_pct: 80,
    staffed_hours_per_day: 9,
  },
  models: { enabled: ['seasonal_naive', 'ridge'] },
};

const PLACEHOLDER_CONFIG: ConfigSummary = {
  forecast: { horizons: [], interval_level: 0, n_simulations: 0, targets: [] },
  cv: {
    horizon: 0,
    step: 0,
    initial_train_days: 0,
    min_folds: 0,
    selection_metric: '',
    selection_tiebreaker: '',
  },
  data: { holiday_country: '', holiday_subdiv: null },
  business_hours: { start_hour: 0, end_hour: 0, overnight_start_hour: 0, overnight_end_hour: 0 },
  anomalies: {
    cost_overrun_pct: 0,
    duration_sigma: 0,
    missed_spike_sigma: 0,
    robust_z_threshold: 0,
    baseline_window_days: 0,
  },
  scenarios: {
    current_agents: 0,
    target_answer_seconds: 0,
    service_level_pct: 0,
    staffed_hours_per_day: 0,
  },
  models: { enabled: [] },
};

const GENERATED_AT = '2026-07-30T15:15:00Z';

describe('DashboardFooter', () => {
  describe('when a pipeline run produced the payload', () => {
    it('reports the run configuration', () => {
      render(
        <DashboardFooter config={REAL_CONFIG} generatedAt={GENERATED_AT} analysisAvailable />,
      );

      expect(screen.getByText(/Interval level: 80%/)).toBeInTheDocument();
      expect(screen.getByText(/selection on MASE/)).toBeInTheDocument();
      expect(screen.getByText(/Holiday calendar: US AZ/)).toBeInTheDocument();
      expect(screen.getByText(/Generated by call_forecast/)).toBeInTheDocument();
    });

    it('keeps the point-forecast reading note, which only makes sense with a forecast', () => {
      render(
        <DashboardFooter config={REAL_CONFIG} generatedAt={GENERATED_AT} analysisAvailable />,
      );

      expect(screen.getByText(/Point forecasts are the model/)).toBeInTheDocument();
    });
  });

  /*
   * The regression this file exists for. Before PR 19 the footer read `config`
   * unconditionally, so a CSV import published the placeholder as fact: an
   * interval level of 0%, zero bootstrap trajectories, a 0-day validation
   * horizon with no metric named, and business hours of 00:00-00:00. Those are
   * not empty states, they are false statements about settings.
   */
  describe('when the payload came from an imported file', () => {
    it('states no configuration rather than reporting the placeholder zeros', () => {
      render(
        <DashboardFooter
          config={PLACEHOLDER_CONFIG}
          generatedAt={GENERATED_AT}
          analysisAvailable={false}
        />,
      );

      expect(screen.queryByText(/Interval level/)).not.toBeInTheDocument();
      expect(screen.queryByText(/bootstrap trajectories/)).not.toBeInTheDocument();
      expect(screen.queryByText(/rolling origin/)).not.toBeInTheDocument();
      expect(screen.queryByText(/Holiday calendar/)).not.toBeInTheDocument();
      expect(screen.queryByText(/Business hours/)).not.toBeInTheDocument();
    });

    it('never renders a zeroed figure anywhere in the footer', () => {
      const { container } = render(
        <DashboardFooter
          config={PLACEHOLDER_CONFIG}
          generatedAt={GENERATED_AT}
          analysisAvailable={false}
        />,
      );

      // The specific strings the bug put on screen, whatever markup they sat in.
      expect(container.textContent).not.toMatch(/0%/);
      expect(container.textContent).not.toMatch(/00:00/);
      expect(container.textContent).not.toMatch(/0-day/);
    });

    it('does not claim call_forecast generated the view', () => {
      render(
        <DashboardFooter
          config={PLACEHOLDER_CONFIG}
          generatedAt={GENERATED_AT}
          analysisAvailable={false}
        />,
      );

      expect(screen.queryByText(/Generated by call_forecast/)).not.toBeInTheDocument();
      expect(screen.getByText(/Rendered from an imported file/)).toBeInTheDocument();
    });

    it('explains why there is no methodology to report', () => {
      render(
        <DashboardFooter
          config={PLACEHOLDER_CONFIG}
          generatedAt={GENERATED_AT}
          analysisAvailable={false}
        />,
      );

      expect(screen.getByText(/No forecast, model selection or anomaly rule ran/)).toBeInTheDocument();
    });
  });
});
