/**
 * The CSV port, checked against the Python pipeline that defines it.
 *
 * `buildFromCsv` is a hand port of `features.build_daily()` and the descriptive
 * half of `ingest.load_calls()`. Unit tests can pin its behaviour on fixtures
 * this repo invented; only this file pins it against the implementation it is
 * supposed to agree with.
 *
 * The two inputs are already committed and already coupled: the fixture at
 * `data/fixtures/dashboard_data.json` is generated by running the pipeline over
 * `examples/sample_export.csv` (see `frontend/README.md`). Feeding that same CSV
 * to the TypeScript path and diffing the daily aggregates is therefore a real
 * comparison of two implementations over one input, not a tautology.
 *
 * **What this can and cannot catch.** It covers aggregation, calendar handling
 * and the null/zero distinction — the parts a reader sees in Data Quality, At a
 * Glance and the arrivals heatmap. It says nothing about forecasts, which the
 * CSV path deliberately does not produce.
 *
 * If this fails after a change to `buildFromCsv`, the port has drifted. If it
 * fails after the fixture is regenerated, check whether `build_daily` changed
 * on the Python side and port the change rather than relaxing the tolerance.
 */
import { describe, expect, it } from 'vitest';
import { buildFromCsv } from './buildFromCsv';
import fixture from '../../data/fixtures/dashboard_data.json';
// Vite's `?raw` rather than `node:fs`. This project's tsconfig deliberately
// carries no Node types — it builds a browser bundle — and adding
// `@types/node` to satisfy one test would widen the app's type surface to
// make a test compile. `?raw` is typed by `vite/client`, which
// `src/vite-env.d.ts` already references.
import csv from '../../../../examples/sample_export.csv?raw';

/** Currency and mean-duration comparisons are float maths in two languages. */
const TOLERANCE = 0.005;

function build() {
  const result = buildFromCsv(csv, 'sample_export.csv', csv.length);
  if (!result.ok) {
    throw new Error(`sample_export.csv failed to parse: ${JSON.stringify(result.errors)}`);
  }
  return result;
}

describe('buildFromCsv agrees with the Python pipeline on examples/sample_export.csv', () => {
  const result = build();
  const mine = result.payload.daily;
  const theirs = fixture.daily as Array<Record<string, number | null | string>>;

  it('reads the same number of call rows', () => {
    expect(result.payload.ingestion.rows_read).toBe(fixture.ingestion.rows_read);
    expect(result.payload.ingestion.rows_kept).toBe(fixture.ingestion.rows_kept);
  });

  it('produces the same daily calendar, zero-call days included', () => {
    expect(mine.map((r) => r.date)).toEqual(theirs.map((r) => r.date));
  });

  it('produces the same value for every target on every day', () => {
    const byDate = new Map(theirs.map((r) => [r.date as string, r]));
    const mismatches: string[] = [];

    for (const row of mine) {
      const ref = byDate.get(row.date as string);
      if (ref === undefined) {
        mismatches.push(`${row.date as string}: absent from the fixture`);
        continue;
      }
      for (const key of ['call_volume', 'total_cost', 'avg_duration_sec'] as const) {
        const a = row[key] as number | null;
        const b = ref[key] as number | null;
        // null is a value here, not a missing one: it means "undefined for a
        // good reason", and a 0 in its place would be a different claim.
        if (a === null || b === null) {
          if (a !== b) mismatches.push(`${row.date as string} ${key}: ts=${a} py=${b}`);
        } else if (Math.abs(a - b) > TOLERANCE) {
          mismatches.push(`${row.date as string} ${key}: ts=${a} py=${b}`);
        }
      }
    }

    expect(mismatches).toEqual([]);
  });

  /*
   * The rule most likely to be broken by a well-meaning refactor: a day with no
   * calls has a volume of 0 and a cost of 0, but its average duration is null,
   * because the mean of no observations is undefined rather than zero. Writing
   * 0 there would bias every downstream model and read as "calls that took no
   * time". Asserted on both sides so the count itself cannot silently drift.
   */
  it('marks zero-call days the same way Python does', () => {
    const tsZero = mine.filter((r) => r.call_volume === 0);
    const pyZero = theirs.filter((r) => r.call_volume === 0);

    expect(tsZero.length).toBe(pyZero.length);
    expect(tsZero.length).toBeGreaterThan(0);
    for (const row of tsZero) {
      expect(row.avg_duration_sec).toBeNull();
      expect(row.total_cost).toBe(0);
    }
  });

  it('bins every call into the same 7x24 arrivals grid', () => {
    const hourly = result.payload.hourly;
    const pyHourly = fixture.hourly as Array<{ weekday: number; hour: number; calls: number }>;

    expect(hourly).toHaveLength(168);
    expect(hourly).toHaveLength(pyHourly.length);

    const key = (c: { weekday: number; hour: number }) => `${c.weekday}:${c.hour}`;
    const pyByCell = new Map(pyHourly.map((c) => [key(c), c.calls]));
    for (const cell of hourly) {
      expect(pyByCell.get(key(cell))).toBe(cell.calls);
    }

    // And the grid accounts for every call, rather than dropping some into a
    // cell that does not exist.
    const total = hourly.reduce((sum, c) => sum + c.calls, 0);
    expect(total).toBe(result.payload.ingestion.rows_kept);
  });
});
